name: first-workflow
on: push

jobs:
  first-workflow:

    runs-on: ubuntu-latest

    steps:
      - name: check repository code
        uses: actions/checkout@v4
      - run: echo "$(cat hello_world.txt)"
